baseURL = "https://xaoirse.github.io/"
languageCode = ["en-us","fa-ir"]
title = "Million Lines Of Code"
theme = "hyde"
[Menus]
  main = [
      {Name = "Categories", URL = "/categories/" ,weight = -1},
      {Name = "Github", URL = "https://github.com/xaoirse/",weight = 100},
      
  ]
[taxonomies]
  category = "categories"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

